### ISSUE TITLE
Parametric shape alignment

### ISSUE THREAD

**Issue by OmerMachluf** [fudan-generative-vision/champ#11]
Hi, thanks for sharing this work -- it looks great!
The paper mentions parametric shape alignment that sounds intriguing. however, i'm not seeing any reference to those models in the codebase. do you plan to release the inference/models for that as well?.

**Comment by i-amgeek** [comment]
@OmerMachluf They have used parametric models to render normals,  masks etc. It would be difficult to use parametric models directly for guidance; so they projected them to 2D images.

**Comment by OmerMachluf** [comment]
> @OmerMachluf They have used parametric models to render normals, masks etc. It would be difficult to use parametric models directly for guidance; so they projected them to 2D images.

@i-amgeek appreciate your response. The question is about the fitting as @sam598 mentioned
The paper mentions fitting one smplx model into the driving video smplx model by displacing the pose from the driving video smplx and transferring it into the new model. I was wondering if there is any available code ref for that because it seems to be a vital step in order to reproduce the results mentioned in the paper for other ref/videos.

**Comment by ShenhaoZhu** [comment]
Thank you for your interest in our work. We are now reorganizing our preprocessing code about Parametric Shape Alignment and will release soon.

**Comment by Leoooo333** [comment]
Hi there, we have released our code for Rendering & SMPL, check the readme for details! And for the parametric shape alignment, we just name it `Transfer SMPL` in the instructions. Try on that!👏

**Comment by OmerMachluf** [comment]
@Leoooo333 
Thanks! Appreciate your contributions to the community :)
I do see the update in the readme and the additional 4d humans submomdule, but I couldn't locate the transfer_smpl.py file that it's referencing in the git or in the last commit that updated the readme, maybe you forgot to attach that file to the commit? :)

**Comment by Leoooo333** [comment]
Hi, it’s in our fork ‘4D-Humans/transfer_smpl.py’.And it need to run in 4D-Hunans conda environment , and would be better to ‘cd’ in the 4D-Humans directory and then dealing with these SMPL & Rendering thing.

**Comment by Leoooo333** [comment]
@OmerMachluf We have released the SMPL & Rending code. Git clone the updated Champ and have a try!

**Comment by AricGamma** [comment]
Closing this issue. If any further questions, please reopen or create a new one.
